server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: env,health
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  banner:
    charset: UTF-8

logging:
  level:
    ROOT: INFO